### ISSUE TITLE
DMS broken when migrate alter data type to redshift.

### ISSUE THREAD

**Issue by YoussefEssa** [awsdocs/aws-dms-user-guide#1]
The source database is postgres and target database is Redshift. So, DMS not able to skip or modify the query not supported by redshift like atler datatype as in the following example:
ALTER TABLE table_name
ALTER COLUMN column_name [SET DATA] TYPE new_data_type;

The DMS task is broken and the solutions to fix this by excluding the table and start the task, or restarting the task from the beginning.

**Comment by davehowell** [comment]
The docs state that this is not supported 
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.Redshift.html


> When using an Amazon Redshift database as a target, AWS DMS doesn't support the following:
> 
>  The following DDL is not supported:

```
    ALTER TABLE <table name> MODIFY COLUMN <column name> <data type>;                   
                    
```

For continuous updating I can't imagine this could ever be supported because it would block the entire table, meaning you'd have to reload/backfill it anyway. Schema evolution sounds nice in theory, but it's both overrated (hard to use for analytics) and unlikely to happen on Redshift, although possibly with Redshift Spectrum.
